/* ============================================================
   Wordbooks · 内置单词书（外贸英语高频词 / 公共常用英语高频词）
   挂载到 window.App.Wordbooks
   每本词书: { id, name, desc, ico, words:[{word,phonetic,meaning,example}] }
   ============================================================ */
(function(){
  window.App = window.App || {};

  App.Wordbooks = [

    /* ======================= 外贸英语高频词 ======================= */
    {
      id: 'trade_en',
      name: '外贸英语高频词',
      desc: '化工外贸全流程核心词汇',
      ico: '💼',
      words: [
        { word:'quotation', phonetic:'/kwəˈweɪʃn/', meaning:'n. 报价（单）', example:'Could you send us a quotation?' },
        { word:'offer', phonetic:'/ˈɒfə/', meaning:'n./v. 报盘，报价', example:'Our offer is valid for 15 days.' },
        { word:'inquiry', phonetic:'/ˈɪŋkwəri/', meaning:'n. 询盘，询价', example:'Thank you for your inquiry.' },
        { word:'counteroffer', phonetic:'/ˈkaʊntərˌɒfə/', meaning:'n. 还价，还盘', example:"We can't accept your counteroffer." },
        { word:'specification', phonetic:'/ˌspesɪfɪˈkeɪʃn/', meaning:'n. 规格，规格说明', example:'Please check the product specification.' },
        { word:'sample', phonetic:'/ˈsɑːmpl/', meaning:'n. 样品', example:"We'll send you free samples." },
        { word:'order', phonetic:'/ˈɔːdə/', meaning:'n. 订单', example:"We'd like to place a trial order." },
        { word:'shipment', phonetic:'/ˈʃɪpmənt/', meaning:'n. 装运，发货', example:'When can you arrange shipment?' },
        { word:'freight', phonetic:'/freɪt/', meaning:'n. 运费', example:'Freight is included in the price.' },
        { word:'container', phonetic:'/kənˈteɪnə/', meaning:'n. 集装箱', example:'We need a 20ft container.' },
        { word:'delivery', phonetic:'/dɪˈlɪvəri/', meaning:'n. 交货，交付', example:'Delivery will be made next week.' },
        { word:'payment', phonetic:'/ˈpeɪmənt/', meaning:'n. 付款', example:'What are your payment terms?' },
        { word:'deposit', phonetic:'/dɪˈpɒzɪt/', meaning:'n. 定金', example:'A 30% deposit is required.' },
        { word:'balance', phonetic:'/ˈbæləns/', meaning:'n. 尾款，余额', example:'The balance is due before shipment.' },
        { word:'invoice', phonetic:'/ˈɪnvɔɪs/', meaning:'n. 发票', example:'Please send the proforma invoice.' },
        { word:'packing', phonetic:'/ˈpækɪŋ/', meaning:'n. 包装', example:'The packing must meet export standards.' },
        { word:'customs', phonetic:'/ˈkʌstəmz/', meaning:'n. 海关', example:'Customs clearance takes two days.' },
        { word:'compliance', phonetic:'/kəmˈplaɪəns/', meaning:'n. 合规', example:'We ensure full regulatory compliance.' },
        { word:'certificate', phonetic:'/səˈtɪfɪkət/', meaning:'n. 证书', example:'We need a Certificate of Analysis.' },
        { word:'inspect', phonetic:'/ɪnˈspekt/', meaning:'v. 检验，检查', example:'Please inspect the goods on arrival.' },
        { word:'contract', phonetic:'/ˈkɒntrækt/', meaning:'n. 合同', example:"Let's sign the sales contract." },
        { word:'terms', phonetic:'/tɜːmz/', meaning:'n. 条款，条件', example:'These are our standard terms.' },
        { word:'supplier', phonetic:'/səˈplaɪə/', meaning:'n. 供应商', example:'We are a reliable supplier.' },
        { word:'manufacturer', phonetic:'/ˌmænjuˈfæktʃərə/', meaning:'n. 制造商', example:"We're the direct manufacturer." },
        { word:'export', phonetic:'/ˈekspɔːt/', meaning:'n./v. 出口', example:'We export chemicals worldwide.' },
        { word:'tariff', phonetic:'/ˈtærɪf/', meaning:'n. 关税', example:'The tariff rate is 5%.' },
        { word:'discount', phonetic:'/ˈdɪskaʊnt/', meaning:'n. 折扣', example:'We offer a 5% discount.' },
        { word:'quantity', phonetic:'/ˈkwɒntəti/', meaning:'n. 数量', example:"What's your minimum quantity?" },
        { word:'quality', phonetic:'/ˈkwɒləti/', meaning:'n. 质量', example:'Quality is our top priority.' },
        { word:'negotiation', phonetic:'/nɪˌɡəʊʃiˈeɪʃn/', meaning:'n. 谈判', example:'The negotiation went well.' },
        { word:'valid', phonetic:'/ˈvælɪd/', meaning:'adj. 有效的', example:'The offer is valid for 15 days.' },
        { word:'expire', phonetic:'/ɪkˈspaɪə/', meaning:'v. 过期', example:'The quotation expires tomorrow.' },
        { word:'deadline', phonetic:'/ˈdedlaɪn/', meaning:'n. 截止日期', example:'We must meet the deadline.' },
        { word:'warehouse', phonetic:'/ˈweəhaʊs/', meaning:'n. 仓库', example:'The goods are in our warehouse.' },
        { word:'inventory', phonetic:'/ˈɪnvəntri/', meaning:'n. 库存', example:'Current inventory is sufficient.' },
        { word:'logistics', phonetic:'/ləˈdʒɪstɪks/', meaning:'n. 物流', example:'We handle all logistics.' },
        { word:'MOQ', phonetic:'/ˌem əʊˈkjuː/', meaning:'n. 起订量 (Minimum Order Quantity)', example:'Our MOQ is 1 ton.' },
        { word:'MSDS', phonetic:'/ˌem es diː es/', meaning:'n. 化学品安全数据表', example:'Please provide the MSDS.' },
        { word:'COA', phonetic:'/ˌsiː əʊ ˈeɪ/', meaning:'n. 检验报告 (Certificate of Analysis)', example:'A COA is attached to each batch.' }
      ]
    },

    /* ======================= 公共常用英语高频词 ======================= */
    {
      id: 'common_en',
      name: '公共常用英语高频词',
      desc: '日常生活与工作高频实用词汇',
      ico: '🌟',
      words: [
        { word:'available', phonetic:'/əˈveɪləbl/', meaning:'adj. 可获得的，可用的', example:'Is this product available?' },
        { word:'provide', phonetic:'/prəˈvaɪd/', meaning:'v. 提供', example:'We provide free samples.' },
        { word:'confirm', phonetic:'/kənˈfɜːm/', meaning:'v. 确认', example:'Please confirm the order.' },
        { word:'schedule', phonetic:'/ˈʃedjuːl/', meaning:'n. 日程，安排', example:"Let's check the schedule." },
        { word:'require', phonetic:'/rɪˈkwaɪə/', meaning:'v. 需要，要求', example:'This requires extra time.' },
        { word:'ensure', phonetic:'/ɪnˈʃʊə/', meaning:'v. 确保', example:'We ensure product quality.' },
        { word:'arrange', phonetic:'/əˈreɪndʒ/', meaning:'v. 安排', example:"I'll arrange the meeting." },
        { word:'consider', phonetic:'/kənˈsɪdə/', meaning:'v. 考虑', example:'Please consider our offer.' },
        { word:'suggest', phonetic:'/səˈdʒest/', meaning:'v. 建议', example:'I suggest we start small.' },
        { word:'explain', phonetic:'/ɪkˈspleɪn/', meaning:'v. 解释', example:'Could you explain the details?' },
        { word:'improve', phonetic:'/ɪmˈpruːv/', meaning:'v. 改善，提高', example:'How can we improve it?' },
        { word:'achieve', phonetic:'/əˈtʃiːv/', meaning:'v. 实现，达成', example:'We achieved our goal.' },
        { word:'manage', phonetic:'/ˈmænɪdʒ/', meaning:'v. 管理，设法', example:'I manage the team.' },
        { word:'receive', phonetic:'/rɪˈsiːv/', meaning:'v. 收到', example:'We received your email.' },
        { word:'deliver', phonetic:'/dɪˈlɪvə/', meaning:'v. 交付，送达', example:'We deliver on time.' },
        { word:'contact', phonetic:'/ˈkɒntækt/', meaning:'v./n. 联系', example:'Contact us anytime.' },
        { word:'expect', phonetic:'/ɪkˈspekt/', meaning:'v. 期待，预期', example:'We expect your reply.' },
        { word:'complete', phonetic:'/kəmˈpliːt/', meaning:'v. 完成', example:'Please complete the form.' },
        { word:'prepare', phonetic:'/prɪˈpeə/', meaning:'v. 准备', example:"We'll prepare the samples." },
        { word:'discuss', phonetic:'/dɪˈskʌs/', meaning:'v. 讨论', example:"Let's discuss the terms." },
        { word:'accept', phonetic:'/əkˈsept/', meaning:'v. 接受', example:'We accept your offer.' },
        { word:'compare', phonetic:'/kəmˈpeə/', meaning:'v. 比较', example:"Let's compare the prices." },
        { word:'reduce', phonetic:'/rɪˈdjuːs/', meaning:'v. 减少，降低', example:'Can we reduce the cost?' },
        { word:'increase', phonetic:'/ɪnˈkriːs/', meaning:'v. 增加', example:'Increase the quantity.' },
        { word:'decide', phonetic:'/dɪˈsaɪd/', meaning:'v. 决定', example:'We decided to proceed.' },
        { word:'prefer', phonetic:'/prɪˈfɜː/', meaning:'v. 更喜欢', example:'We prefer T/T payment.' },
        { word:'agree', phonetic:'/əˈɡriː/', meaning:'v. 同意', example:'We agree on the terms.' },
        { word:'cancel', phonetic:'/ˈkænsl/', meaning:'v. 取消', example:"Don't cancel the order." },
        { word:'delay', phonetic:'/dɪˈleɪ/', meaning:'n./v. 延迟', example:'Avoid any delay.' },
        { word:'replace', phonetic:'/rɪˈpleɪs/', meaning:'v. 替换', example:'Can we replace the item?' },
        { word:'service', phonetic:'/ˈsɜːvɪs/', meaning:'n. 服务', example:'Good service matters.' },
        { word:'information', phonetic:'/ˌɪnfəˈmeɪʃn/', meaning:'n. 信息', example:'For more information, contact us.' },
        { word:'situation', phonetic:'/ˌsɪtʃuˈeɪʃn/', meaning:'n. 情况，状况', example:'The situation is stable.' },
        { word:'experience', phonetic:'/ɪkˈspɪəriəns/', meaning:'n. 经验', example:'We have rich experience.' },
        { word:'opportunity', phonetic:'/ˌɒpəˈtjuːnəti/', meaning:'n. 机会', example:'This is a great opportunity.' },
        { word:'problem', phonetic:'/ˈprɒbləm/', meaning:'n. 问题', example:'We solved the problem.' },
        { word:'solution', phonetic:'/səˈluːʃn/', meaning:'n. 解决方案', example:"Here's a solution." },
        { word:'difference', phonetic:'/ˈdɪfrəns/', meaning:'n. 差异', example:"What's the difference?" },
        { word:'reason', phonetic:'/ˈriːzn/', meaning:'n. 原因', example:'The reason is clear.' },
        { word:'result', phonetic:'/rɪˈzʌlt/', meaning:'n. 结果', example:'The result is satisfactory.' }
      ]
    },

    /* ======================= BEC 高频词汇 ======================= */
    {
      id: 'bec',
      name: 'BEC 高频词汇',
      desc: '剑桥商务英语证书核心词汇',
      ico: '📊',
      words: [
        { word:'agenda', phonetic:'/əˈdʒendə/', meaning:'n. 议程', example:'Start with the agenda, please.' },
        { word:'minutes', phonetic:'/ˈmɪnɪts/', meaning:'n. 会议纪要', example:'Who will take the minutes?' },
        { word:'deadline', phonetic:'/ˈdedlaɪn/', meaning:'n. 截止日期', example:'We must meet the deadline.' },
        { word:'budget', phonetic:'/ˈbʌdʒɪt/', meaning:'n. 预算', example:'The budget is tight this year.' },
        { word:'revenue', phonetic:'/ˈrevənjuː/', meaning:'n. 营收', example:'Revenue rose by ten percent.' },
        { word:'profit', phonetic:'/ˈprɒfɪt/', meaning:'n. 利润', example:'We made a good profit.' },
        { word:'expense', phonetic:'/ɪkˈspens/', meaning:'n. 支出', example:'Travel expenses are covered.' },
        { word:'invoice', phonetic:'/ˈɪnvɔɪs/', meaning:'n. 发票', example:'Please issue the invoice.' },
        { word:'refund', phonetic:'/ˈriːfʌnd/', meaning:'n./v. 退款', example:'We offer a full refund.' },
        { word:'discount', phonetic:'/ˈdɪskaʊnt/', meaning:'n. 折扣', example:'A bulk discount is available.' },
        { word:'turnover', phonetic:'/ˈtɜːnəʊvə/', meaning:'n. 营业额', example:'Annual turnover hit a record.' },
        { word:'assets', phonetic:'/ˈæsets/', meaning:'n. 资产', example:'The company assets are growing.' },
        { word:'liability', phonetic:'/ˌlaɪəˈbɪləti/', meaning:'n. 负债', example:'We need to reduce liabilities.' },
        { word:'bankruptcy', phonetic:'/ˈbæŋkrʌptsi/', meaning:'n. 破产', example:'They filed for bankruptcy.' },
        { word:'merger', phonetic:'/ˈmɜːdʒə/', meaning:'n. 合并', example:'The merger was approved.' },
        { word:'acquisition', phonetic:'/ˌækwɪˈzɪʃn/', meaning:'n. 收购', example:'It was a strategic acquisition.' },
        { word:'franchise', phonetic:'/ˈfræntʃaɪz/', meaning:'n. 特许经营', example:'We run a franchise model.' },
        { word:'tender', phonetic:'/ˈtendə/', meaning:'n. 招标', example:'We won the government tender.' },
        { word:'bid', phonetic:'/bɪd/', meaning:'n./v. 投标', example:'Our bid was the lowest.' },
        { word:'proposal', phonetic:'/prəˈpəʊzl/', meaning:'n. 提案', example:'Please review our proposal.' },
        { word:'negotiate', phonetic:'/nɪˈɡəʊʃieɪt/', meaning:'v. 谈判', example:'Let us negotiate the terms.' },
        { word:'consensus', phonetic:'/kənˈsensəs/', meaning:'n. 共识', example:'We reached a consensus.' },
        { word:'compromise', phonetic:'/ˈkɒmprəmaɪz/', meaning:'n./v. 妥协', example:'Both sides made a compromise.' },
        { word:'strategy', phonetic:'/ˈstrætədʒi/', meaning:'n. 战略', example:'Share our marketing strategy.' },
        { word:'competitor', phonetic:'/kəmˈpetɪtə/', meaning:'n. 竞争对手', example:'A competitor lowered prices.' },
        { word:'forecast', phonetic:'/ˈfɔːkɑːst/', meaning:'n./v. 预测', example:'The sales forecast looks good.' },
        { word:'launch', phonetic:'/lɔːntʃ/', meaning:'v. 发布', example:'We will launch next month.' },
        { word:'campaign', phonetic:'/kæmˈpeɪn/', meaning:'n. 营销活动', example:'The ad campaign was a hit.' },
        { word:'endorse', phonetic:'/ɪnˈdɔːs/', meaning:'v. 背书；代言', example:'The star endorsed our brand.' },
        { word:'retain', phonetic:'/rɪˈteɪn/', meaning:'v. 保留', example:'We aim to retain key staff.' },
        { word:'recruit', phonetic:'/rɪˈkruːt/', meaning:'v. 招聘', example:'We are recruiting new staff.' },
        { word:'lay off', phonetic:'/leɪ ɒf/', meaning:'v. 裁员', example:'The firm laid off workers.' },
        { word:'resign', phonetic:'/rɪˈzaɪn/', meaning:'v. 辞职', example:'He resigned last week.' },
        { word:'appraisal', phonetic:'/əˈpreɪzl/', meaning:'n. 评估', example:'Annual performance appraisal.' },
        { word:'incentive', phonetic:'/ɪnˈsentɪv/', meaning:'n. 激励', example:'A bonus is a good incentive.' },
        { word:'commission', phonetic:'/kəˈmɪʃn/', meaning:'n. 佣金', example:'Sales staff get a commission.' },
        { word:'deficit', phonetic:'/ˈdefɪsɪt/', meaning:'n. 赤字', example:'The firm ran a deficit.' },
        { word:'audit', phonetic:'/ˈɔːdɪt/', meaning:'n./v. 审计', example:'An annual audit is required.' },
        { word:'inventory', phonetic:'/ˈɪnvəntri/', meaning:'n. 库存', example:'Check the inventory levels.' },
        { word:'dispatch', phonetic:'/dɪˈspætʃ/', meaning:'v. 发货', example:'We will dispatch the goods today.' }
      ]
    },

    /* ======================= PETS-3 三级词汇 ======================= */
    {
      id: 'pets3',
      name: 'PETS-3 三级词汇',
      desc: '全国公共英语等级考试三级高频词',
      ico: '🎓',
      words: [
        { word:'ability', phonetic:'/əˈbɪləti/', meaning:'n. 能力', example:'She has the ability to lead.' },
        { word:'accept', phonetic:'/əkˈsept/', meaning:'v. 接受', example:'I accept your apology.' },
        { word:'achieve', phonetic:'/əˈtʃiːv/', meaning:'v. 实现', example:'He achieved his dream.' },
        { word:'actual', phonetic:'/ˈæktʃuəl/', meaning:'adj. 实际的', example:'The actual cost was higher.' },
        { word:'advantage', phonetic:'/ədˈvɑːntɪdʒ/', meaning:'n. 优势', example:'It has many advantages.' },
        { word:'adventure', phonetic:'/ədˈventʃə/', meaning:'n. 冒险', example:'Life is an adventure.' },
        { word:'affect', phonetic:'/əˈfekt/', meaning:'v. 影响', example:'Weather affects our mood.' },
        { word:'agreement', phonetic:'/əˈɡriːmənt/', meaning:'n. 协议', example:'We signed an agreement.' },
        { word:'ancient', phonetic:'/ˈeɪnʃənt/', meaning:'adj. 古老的', example:'It is an ancient city.' },
        { word:'announce', phonetic:'/əˈnaʊns/', meaning:'v. 宣布', example:'They announced the news.' },
        { word:'anxious', phonetic:'/ˈæŋkʃəs/', meaning:'adj. 焦虑的', example:'She felt anxious.' },
        { word:'appreciate', phonetic:'/əˈpriːʃieɪt/', meaning:'v. 欣赏；感激', example:'I appreciate your help.' },
        { word:'approach', phonetic:'/əˈprəʊtʃ/', meaning:'n./v. 方法；接近', example:'Try a new approach to learning.' },
        { word:'arrange', phonetic:'/əˈreɪndʒ/', meaning:'v. 安排', example:'I will arrange a meeting.' },
        { word:'atmosphere', phonetic:'/ˈætməsfɪə/', meaning:'n. 气氛', example:'It has a friendly atmosphere.' },
        { word:'attend', phonetic:'/əˈtend/', meaning:'v. 出席', example:'I will attend the meeting.' },
        { word:'audience', phonetic:'/ˈɔːdiəns/', meaning:'n. 观众', example:'The audience applauded.' },
        { word:'balance', phonetic:'/ˈbæləns/', meaning:'n. 平衡', example:'Keep a good balance.' },
        { word:'behavior', phonetic:'/bɪˈheɪvjə/', meaning:'n. 行为', example:'His behavior was strange.' },
        { word:'believe', phonetic:'/bɪˈliːv/', meaning:'v. 相信', example:'I believe you.' },
        { word:'benefit', phonetic:'/ˈbenɪfɪt/', meaning:'n. 好处', example:'Exercise has many benefits.' },
        { word:'brief', phonetic:'/briːf/', meaning:'adj. 简短的', example:'Give a brief introduction.' },
        { word:'capable', phonetic:'/ˈkeɪpəbl/', meaning:'adj. 有能力的', example:'She is capable of it.' },
        { word:'cause', phonetic:'/kɔːz/', meaning:'n. 原因', example:'Tell me the cause.' },
        { word:'challenge', phonetic:'/ˈtʃælɪndʒ/', meaning:'n. 挑战', example:'Life is full of challenges.' },
        { word:'character', phonetic:'/ˈkærəktə/', meaning:'n. 性格', example:'He has a strong character.' },
        { word:'charge', phonetic:'/tʃɑːdʒ/', meaning:'v. 收费；负责', example:'Who is in charge?' },
        { word:'communicate', phonetic:'/kəˈmjuːnɪkeɪt/', meaning:'v. 交流', example:'We communicate by email.' },
        { word:'compare', phonetic:'/kəmˈpeə/', meaning:'v. 比较', example:'Compare the two options.' },
        { word:'complain', phonetic:'/kəmˈpleɪn/', meaning:'v. 抱怨', example:'Do not complain too much.' },
        { word:'complete', phonetic:'/kəmˈpliːt/', meaning:'adj./v. 完整；完成', example:'Please complete the task.' },
        { word:'confident', phonetic:'/ˈkɒnfɪdənt/', meaning:'adj. 自信的', example:'She is confident.' },
        { word:'consider', phonetic:'/kənˈsɪdə/', meaning:'v. 考虑', example:'Please consider it.' },
        { word:'contain', phonetic:'/kənˈteɪn/', meaning:'v. 包含', example:'The box contains books.' },
        { word:'continue', phonetic:'/kənˈtɪnjuː/', meaning:'v. 继续', example:'Please continue.' },
        { word:'convenience', phonetic:'/kənˈviːniəns/', meaning:'n. 便利', example:'For your convenience.' },
        { word:'courage', phonetic:'/ˈkʌrɪdʒ/', meaning:'n. 勇气', example:'He has courage.' },
        { word:'creature', phonetic:'/ˈkriːtʃə/', meaning:'n. 生物', example:'It is a lovely creature.' },
        { word:'decision', phonetic:'/dɪˈsɪʒn/', meaning:'n. 决定', example:'Make a decision now.' },
        { word:'depend', phonetic:'/dɪˈpend/', meaning:'v. 依赖', example:'It depends on you.' }
      ]
    },

    /* ======================= CET-4 四级高频词 ======================= */
    {
      id: 'cet4',
      name: 'CET-4 四级高频词',
      desc: '大学英语四级核心词汇',
      ico: '📗',
      words: [
        { word:'absorb', phonetic:'/əbˈzɔːb/', meaning:'v. 吸收', example:'The paper absorbs water.' },
        { word:'abstract', phonetic:'/ˈæbstrækt/', meaning:'adj. 抽象的', example:'Love is an abstract concept.' },
        { word:'abundant', phonetic:'/əˈbʌndənt/', meaning:'adj. 丰富的', example:'We have abundant resources.' },
        { word:'academic', phonetic:'/ˌækəˈdemɪk/', meaning:'adj. 学术的', example:'She has an academic background.' },
        { word:'accomplish', phonetic:'/əˈkʌmplɪʃ/', meaning:'v. 完成', example:'We accomplished the task.' },
        { word:'accurate', phonetic:'/ˈækjərət/', meaning:'adj. 准确的', example:'The data is accurate.' },
        { word:'acquire', phonetic:'/əˈkwaɪə/', meaning:'v. 获得', example:'He acquired new skills.' },
        { word:'adapt', phonetic:'/əˈdæpt/', meaning:'v. 适应', example:'We must adapt to changes.' },
        { word:'adequate', phonetic:'/ˈædɪkwət/', meaning:'adj. 充足的', example:'The supply is adequate.' },
        { word:'adjust', phonetic:'/əˈdʒʌst/', meaning:'v. 调整', example:'Please adjust the volume.' },
        { word:'admire', phonetic:'/ədˈmaɪə/', meaning:'v. 钦佩', example:'I admire his courage.' },
        { word:'adopt', phonetic:'/əˈdɒpt/', meaning:'v. 采纳', example:'We adopted a new method.' },
        { word:'advance', phonetic:'/ədˈvɑːns/', meaning:'v. 前进', example:'Technology advances fast.' },
        { word:'advocate', phonetic:'/ˈædvəkeɪt/', meaning:'v. 提倡', example:'She advocates healthy eating.' },
        { word:'allocate', phonetic:'/ˈæləkeɪt/', meaning:'v. 分配', example:'We allocate funds wisely.' },
        { word:'alter', phonetic:'/ˈɔːltə/', meaning:'v. 改变', example:'The plan was altered.' },
        { word:'alternative', phonetic:'/ɔːlˈtɜːnətɪv/', meaning:'n. 替代方案', example:'We need an alternative.' },
        { word:'analyze', phonetic:'/ˈænəlaɪz/', meaning:'v. 分析', example:'Let us analyze the data.' },
        { word:'annual', phonetic:'/ˈænjʊəl/', meaning:'adj. 年度的', example:'We hold an annual meeting.' },
        { word:'apparent', phonetic:'/əˈpærənt/', meaning:'adj. 明显的', example:'It is apparent to all.' },
        { word:'appeal', phonetic:'/əˈpiːl/', meaning:'v. 吸引；呼吁', example:'The design appeals to me.' },
        { word:'apply', phonetic:'/əˈplaɪ/', meaning:'v. 申请', example:'I will apply for the job.' },
        { word:'appoint', phonetic:'/əˈpɔɪnt/', meaning:'v. 任命', example:'She was appointed manager.' },
        { word:'appropriate', phonetic:'/əˈprəʊpriət/', meaning:'adj. 合适的', example:'Wear appropriate clothes.' },
        { word:'approve', phonetic:'/əˈpruːv/', meaning:'v. 批准', example:'The board approved it.' },
        { word:'assume', phonetic:'/əˈsjuːm/', meaning:'v. 假设', example:'Do not assume anything.' },
        { word:'attach', phonetic:'/əˈtætʃ/', meaning:'v. 附加', example:'Attach the file here.' },
        { word:'attain', phonetic:'/əˈteɪn/', meaning:'v. 达到', example:'He attained his goal.' },
        { word:'attribute', phonetic:'/əˈtrɪbjuːt/', meaning:'v. 归因', example:'She attributes success to hard work.' },
        { word:'authentic', phonetic:'/ɔːˈθentɪk/', meaning:'adj. 真正的', example:'It is an authentic signature.' },
        { word:'authority', phonetic:'/ɔːˈθɒrəti/', meaning:'n. 权威', example:'She is an authority on this.' },
        { word:'available', phonetic:'/əˈveɪləbl/', meaning:'adj. 可获得的', example:'The book is available.' },
        { word:'aware', phonetic:'/əˈweə/', meaning:'adj. 意识到的', example:'I am aware of the risk.' },
        { word:'bargain', phonetic:'/ˈbɑːɡɪn/', meaning:'n. 廉价货', example:'It was a real bargain.' },
        { word:'barrier', phonetic:'/ˈbæriə/', meaning:'n. 障碍', example:'Language is a barrier.' },
        { word:'behalf', phonetic:'/bɪˈhɑːf/', meaning:'n. 代表', example:'I speak on your behalf.' },
        { word:'blast', phonetic:'/blɑːst/', meaning:'n. 爆炸', example:'The blast was heard far away.' },
        { word:'boost', phonetic:'/buːst/', meaning:'v. 促进', example:'Exercise boosts health.' },
        { word:'boundary', phonetic:'/ˈbaʊndri/', meaning:'n. 边界', example:'The river is the boundary.' }
      ]
    },

    /* ======================= CET-6 六级高频词 ======================= */
    {
      id: 'cet6',
      name: 'CET-6 六级高频词',
      desc: '大学英语六级核心词汇',
      ico: '📘',
      words: [
        { word:'accumulate', phonetic:'/əˈkjuːmjəleɪt/', meaning:'v. 积累', example:'He accumulated wealth.' },
        { word:'acute', phonetic:'/əˈkjuːt/', meaning:'adj. 急性的；敏锐的', example:'An acute sense of smell.' },
        { word:'adjacent', phonetic:'/əˈdʒeɪsnt/', meaning:'adj. 毗邻的', example:'The two rooms are adjacent.' },
        { word:'ambiguous', phonetic:'/æmˈbɪɡjuəs/', meaning:'adj. 模糊的', example:'His answer was ambiguous.' },
        { word:'analogy', phonetic:'/əˈnælədʒi/', meaning:'n. 类比', example:'Draw an analogy here.' },
        { word:'anonymous', phonetic:'/əˈnɒnɪməs/', meaning:'adj. 匿名的', example:'An anonymous donor.' },
        { word:'anticipate', phonetic:'/ænˈtɪsɪpeɪt/', meaning:'v. 预期', example:'We anticipate problems.' },
        { word:'assemble', phonetic:'/əˈsembl/', meaning:'v. 组装', example:'They assemble cars here.' },
        { word:'assess', phonetic:'/əˈses/', meaning:'v. 评估', example:'We must assess the risk.' },
        { word:'assign', phonetic:'/əˈsaɪn/', meaning:'v. 分配', example:'Assign tasks to the team.' },
        { word:'assimilate', phonetic:'/əˈsɪməleɪt/', meaning:'v. 同化', example:'Immigrants assimilate slowly.' },
        { word:'augment', phonetic:'/ɔːɡˈment/', meaning:'v. 增加', example:'We augment our income.' },
        { word:'autonomy', phonetic:'/ɔːˈtɒnəmi/', meaning:'n. 自治', example:'They demand autonomy.' },
        { word:'bizarre', phonetic:'/bɪˈzɑː/', meaning:'adj. 奇异的', example:'A bizarre story.' },
        { word:'breakdown', phonetic:'/ˈbreɪkdaʊn/', meaning:'n. 故障', example:'A breakdown of the car.' },
        { word:'capability', phonetic:'/ˌkeɪpəˈbɪləti/', meaning:'n. 能力', example:'We have the capability.' },
        { word:'chronic', phonetic:'/ˈkrɒnɪk/', meaning:'adj. 慢性的', example:'A chronic disease.' },
        { word:'coincide', phonetic:'/ˌkəʊɪnˈsaɪd/', meaning:'v. 巧合', example:'Our trips coincide.' },
        { word:'collaborate', phonetic:'/kəˈlæbəreɪt/', meaning:'v. 合作', example:'We collaborate with them.' },
        { word:'competent', phonetic:'/ˈkɒmpɪtənt/', meaning:'adj. 胜任的', example:'She is a competent leader.' },
        { word:'compulsory', phonetic:'/kəmˈpʌlsəri/', meaning:'adj. 强制的', example:'Education is compulsory.' },
        { word:'concise', phonetic:'/kənˈsaɪs/', meaning:'adj. 简洁的', example:'A concise summary.' },
        { word:'correlate', phonetic:'/ˈkɒrəleɪt/', meaning:'v. 相关', example:'The two factors correlate.' },
        { word:'counterpart', phonetic:'/ˈkaʊntəpɑːt/', meaning:'n. 对应物', example:'Talk to our counterpart.' },
        { word:'crucial', phonetic:'/ˈkruːʃl/', meaning:'adj. 关键的', example:'It is a crucial moment.' },
        { word:'dedicate', phonetic:'/ˈdedɪkeɪt/', meaning:'v. 奉献', example:'She dedicated her life to it.' },
        { word:'deliberate', phonetic:'/dɪˈlɪbərət/', meaning:'adj. 蓄意的', example:'A deliberate attempt.' },
        { word:'democratic', phonetic:'/ˌdeməˈkrætɪk/', meaning:'adj. 民主的', example:'A democratic vote.' },
        { word:'demonstrate', phonetic:'/ˈdemənstreɪt/', meaning:'v. 证明；演示', example:'Let me demonstrate.' },
        { word:'denote', phonetic:'/dɪˈnəʊt/', meaning:'v. 表示', example:'Red denotes danger.' },
        { word:'deploy', phonetic:'/dɪˈplɔɪ/', meaning:'v. 部署', example:'We deploy new software.' },
        { word:'derive', phonetic:'/dɪˈraɪv/', meaning:'v. 源于', example:'The word derives from Latin.' },
        { word:'dilemma', phonetic:'/dɪˈlemə/', meaning:'n. 困境', example:'I face a dilemma.' },
        { word:'diminish', phonetic:'/dɪˈmɪnɪʃ/', meaning:'v. 减少', example:'The risk diminished.' },
        { word:'dispose', phonetic:'/dɪˈspəʊz/', meaning:'v. 处理', example:'Dispose of the waste.' },
        { word:'distort', phonetic:'/dɪˈstɔːt/', meaning:'v. 扭曲', example:'The mirror distorts images.' },
        { word:'diverse', phonetic:'/daɪˈvɜːs/', meaning:'adj. 多样的', example:'A diverse culture.' },
        { word:'dominate', phonetic:'/ˈdɒmɪneɪt/', meaning:'v. 主导', example:'One company dominates.' },
        { word:'dwell', phonetic:'/dwel/', meaning:'v. 居住', example:'She dwells in the city.' },
        { word:'eligible', phonetic:'/ˈelɪdʒəbl/', meaning:'adj. 合格的', example:'You are eligible to apply.' }
      ]
    },

    /* ======================= IELTS 雅思高频词 ======================= */
    {
      id: 'ielts',
      name: 'IELTS 雅思高频词',
      desc: '雅思考试学术高频词汇',
      ico: '🟣',
      words: [
        { word:'abandon', phonetic:'/əˈbændən/', meaning:'v. 放弃', example:'They abandoned the plan.' },
        { word:'accommodate', phonetic:'/əˈkɒmədeɪt/', meaning:'v. 容纳', example:'The hall can accommodate 200.' },
        { word:'administration', phonetic:'/ədˌmɪnɪˈstreɪʃn/', meaning:'n. 管理', example:'The administration is efficient.' },
        { word:'aesthetic', phonetic:'/iːsˈθetɪk/', meaning:'adj. 审美的', example:'An aesthetic design.' },
        { word:'afford', phonetic:'/əˈfɔːd/', meaning:'v. 负担得起', example:'I cannot afford it.' },
        { word:'agriculture', phonetic:'/ˈæɡrɪkʌltʃə/', meaning:'n. 农业', example:'Agriculture is vital here.' },
        { word:'aircraft', phonetic:'/ˈeəkrɑːft/', meaning:'n. 飞机', example:'The aircraft landed safely.' },
        { word:'alteration', phonetic:'/ˌɔːltəˈreɪʃn/', meaning:'n. 改动', example:'A small alteration.' },
        { word:'ambition', phonetic:'/æmˈbɪʃn/', meaning:'n. 抱负', example:'She has great ambition.' },
        { word:'animate', phonetic:'/ˈænɪmeɪt/', meaning:'v. 使生动', example:'The story was animated.' },
        { word:'antique', phonetic:'/ænˈtiːk/', meaning:'n. 古董', example:'He collects antiques.' },
        { word:'appliance', phonetic:'/əˈplaɪəns/', meaning:'n. 家电', example:'A kitchen appliance.' },
        { word:'approximate', phonetic:'/əˈprɒksɪmət/', meaning:'adj. 近似的', example:'The approximate number is 50.' },
        { word:'arbitrary', phonetic:'/ˈɑːbɪtrəri/', meaning:'adj. 任意的', example:'An arbitrary decision.' },
        { word:'assert', phonetic:'/əˈsɜːt/', meaning:'v. 断言', example:'He asserted his rights.' },
        { word:'assist', phonetic:'/əˈsɪst/', meaning:'v. 协助', example:'I will assist you.' },
        { word:'assumption', phonetic:'/əˈsʌmpʃn/', meaning:'n. 假设', example:'That is a wrong assumption.' },
        { word:'attempt', phonetic:'/əˈtempt/', meaning:'n./v. 尝试', example:'Make an attempt.' },
        { word:'aviation', phonetic:'/ˌeɪviˈeɪʃn/', meaning:'n. 航空', example:'The aviation industry.' },
        { word:'barren', phonetic:'/ˈbærən/', meaning:'adj. 荒芜的', example:'A barren desert.' },
        { word:'behave', phonetic:'/bɪˈheɪv/', meaning:'v. 表现', example:'He behaved well.' },
        { word:'beneficial', phonetic:'/ˌbenɪˈfɪʃl/', meaning:'adj. 有益的', example:'Exercise is beneficial.' },
        { word:'biological', phonetic:'/ˌbaɪəˈlɒdʒɪkl/', meaning:'adj. 生物的', example:'A biological process.' },
        { word:'blame', phonetic:'/bleɪm/', meaning:'v. 责备', example:'Do not blame others.' },
        { word:'breadth', phonetic:'/bredθ/', meaning:'n. 宽度', example:'The breadth of the river.' },
        { word:'bulk', phonetic:'/bʌlk/', meaning:'n. 大量', example:'We buy in bulk.' },
        { word:'capacity', phonetic:'/kəˈpæsəti/', meaning:'n. 容量', example:'The capacity is 500.' },
        { word:'category', phonetic:'/ˈkætəɡri/', meaning:'n. 类别', example:'It falls into this category.' },
        { word:'ceremony', phonetic:'/ˈserəməni/', meaning:'n. 仪式', example:'A wedding ceremony.' },
        { word:'characteristic', phonetic:'/ˌkærəktəˈrɪstɪk/', meaning:'n. 特征', example:'A key characteristic.' },
        { word:'charity', phonetic:'/ˈtʃærəti/', meaning:'n. 慈善', example:'She works for a charity.' },
        { word:'chronological', phonetic:'/ˌkrɒnəˈlɒdʒɪkl/', meaning:'adj. 按时间顺序的', example:'A chronological order.' },
        { word:'circulate', phonetic:'/ˈsɜːkjəleɪt/', meaning:'v. 循环', example:'Blood circulates in the body.' },
        { word:'classify', phonetic:'/ˈklæsɪfaɪ/', meaning:'v. 分类', example:'Classify these words.' },
        { word:'climate', phonetic:'/ˈklaɪmət/', meaning:'n. 气候', example:'A warm climate.' },
        { word:'coarse', phonetic:'/kɔːs/', meaning:'adj. 粗糙的', example:'Coarse sandpaper.' },
        { word:'cognitive', phonetic:'/ˈkɒɡnətɪv/', meaning:'adj. 认知的', example:'Cognitive ability.' },
        { word:'coherent', phonetic:'/kəʊˈhɪərənt/', meaning:'adj. 连贯的', example:'A coherent argument.' },
        { word:'collapse', phonetic:'/kəˈlæps/', meaning:'v. 倒塌', example:'The building collapsed.' },
        { word:'commodity', phonetic:'/kəˈmɒdəti/', meaning:'n. 商品', example:'Oil is a key commodity.' }
      ]
    },

    /* ======================= 化工行业专用词汇 ======================= */
    {
      id: 'industry',
      name: '化工行业专用词',
      desc: '化工外贸专业术语',
      ico: '⚗️',
      words: [
        { word:'catalyst', phonetic:'/ˈkætəlɪst/', meaning:'n. 催化剂', example:'Add a catalyst to speed it up.' },
        { word:'polymer', phonetic:'/ˈpɒlɪmə/', meaning:'n. 聚合物', example:'This polymer is flexible.' },
        { word:'solvent', phonetic:'/ˈsɒlvənt/', meaning:'n. 溶剂', example:'Use a safe solvent.' },
        { word:'resin', phonetic:'/ˈrezɪn/', meaning:'n. 树脂', example:'Epoxy resin is common.' },
        { word:'pigment', phonetic:'/ˈpɪɡmənt/', meaning:'n. 颜料', example:'The pigment is non-toxic.' },
        { word:'additive', phonetic:'/ˈædətɪv/', meaning:'n. 添加剂', example:'Food additives are regulated.' },
        { word:'reagent', phonetic:'/riˈeɪdʒənt/', meaning:'n. 试剂', example:'A chemical reagent.' },
        { word:'monomer', phonetic:'/ˈmɒnəmə/', meaning:'n. 单体', example:'The monomer is reactive.' },
        { word:'ester', phonetic:'/ˈestə/', meaning:'n. 酯', example:'This ester smells sweet.' },
        { word:'alkali', phonetic:'/ˈælkəlaɪ/', meaning:'n. 碱', example:'Alkali reacts with acid.' },
        { word:'oxide', phonetic:'/ˈɒksaɪd/', meaning:'n. 氧化物', example:'Zinc oxide is white.' },
        { word:'viscosity', phonetic:'/vɪˈskɒsəti/', meaning:'n. 黏度', example:'Check the viscosity.' },
        { word:'purity', phonetic:'/ˈpjʊərəti/', meaning:'n. 纯度', example:'The purity is 99 percent.' },
        { word:'concentration', phonetic:'/ˌkɒnsənˈtreɪʃn/', meaning:'n. 浓度', example:'High concentration is dangerous.' },
        { word:'batch', phonetic:'/bætʃ/', meaning:'n. 批次', example:'We produce in batches.' },
        { word:'blend', phonetic:'/blend/', meaning:'v./n. 混合', example:'Blend the two liquids.' },
        { word:'formulation', phonetic:'/ˌfɔːmjuˈleɪʃn/', meaning:'n. 配方', example:'A new formulation.' },
        { word:'pellet', phonetic:'/ˈpelɪt/', meaning:'n. 颗粒', example:'Plastic pellets.' },
        { word:'granule', phonetic:'/ˈɡrænjuːl/', meaning:'n. 颗粒', example:'White granules.' },
        { word:'coating', phonetic:'/ˈkəʊtɪŋ/', meaning:'n. 涂层', example:'A protective coating.' },
        { word:'emulsion', phonetic:'/ɪˈmʌlʃn/', meaning:'n. 乳液', example:'An oil emulsion.' },
        { word:'surfactant', phonetic:'/sɜːˈfæktənt/', meaning:'n. 表面活性剂', example:'A surfactant reduces tension.' },
        { word:'stabilizer', phonetic:'/ˈsteɪbəlaɪzə/', meaning:'n. 稳定剂', example:'Add a stabilizer.' },
        { word:'plasticizer', phonetic:'/ˈplæstɪsaɪzə/', meaning:'n. 增塑剂', example:'A plasticizer softens plastic.' },
        { word:'hazardous', phonetic:'/ˈhæzədəs/', meaning:'adj. 危险的', example:'Hazardous waste.' },
        { word:'toxicity', phonetic:'/tɒkˈsɪsəti/', meaning:'n. 毒性', example:'Low toxicity is safe.' },
        { word:'corrosion', phonetic:'/kəˈrəʊʒn/', meaning:'n. 腐蚀', example:'It resists corrosion.' },
        { word:'volatile', phonetic:'/ˈvɒlətaɪl/', meaning:'adj. 挥发性的', example:'A volatile liquid.' },
        { word:'flammable', phonetic:'/ˈflæməbl/', meaning:'adj. 易燃的', example:'Flammable goods.' },
        { word:'polymerization', phonetic:'/ˌpɒlɪməraɪˈzeɪʃn/', meaning:'n. 聚合', example:'The polymerization process.' },
        { word:'stoichiometry', phonetic:'/ˌstɔɪkiˈɒmətri/', meaning:'n. 化学计量', example:'Calculate the stoichiometry.' },
        { word:'hydrolysis', phonetic:'/haɪˈdrɒlɪsɪs/', meaning:'n. 水解', example:'Hydrolysis breaks it down.' },
        { word:'oxidation', phonetic:'/ˌɒksɪˈdeɪʃn/', meaning:'n. 氧化', example:'Oxidation causes rust.' },
        { word:'synthesis', phonetic:'/ˈsɪnθəsɪs/', meaning:'n. 合成', example:'Chemical synthesis.' },
        { word:'titration', phonetic:'/taɪˈtreɪʃn/', meaning:'n. 滴定', example:'Do a titration test.' },
        { word:'volatility', phonetic:'/ˌvɒləˈtɪləti/', meaning:'n. 挥发性', example:'High volatility is risky.' },
        { word:'impurity', phonetic:'/ɪmˈpjʊərəti/', meaning:'n. 杂质', example:'Remove the impurity.' },
        { word:'reactivity', phonetic:'/ˌriːækˈtɪvəti/', meaning:'n. 反应性', example:'High reactivity is dangerous.' },
        { word:'byproduct', phonetic:'/ˈbaɪprɒdʌkt/', meaning:'n. 副产物', example:'A useful byproduct.' },
        { word:'compound', phonetic:'/ˈkɒmpaʊnd/', meaning:'n. 化合物', example:'A chemical compound.' }
      ]
    }

  ];
})();
